echo "//This file is automatically generated by build.sh\n" > App.pde
cat Point.pde >> App.pde
cat Color.pde >> App.pde
cat Circle.pde >> App.pde
cat DragGesture.pde >> App.pde
cat Main.pde >> App.pde
